export type DomainErrorCode =
  | "INVALID_MONEY"
  | "INVALID_UNIT_PRICE"
  | "PURCHASE_AMOUNT_TOO_SMALL"
  | "HISTORICAL_AMOUNT_TOO_SMALL"
  | "INSTRUMENT_NOT_TRADABLE"
  | "INSUFFICIENT_FUNDS"
  | "PREVIEW_NOT_FOUND"
  | "PREVIEW_EXPIRED"
  | "PREVIEW_ALREADY_USED"
  | "IDEMPOTENCY_CONFLICT"
  | "INVALID_SCALE"
  | "INVALID_CURRENCY"
  | "CURRENCY_MISMATCH"
  | "PORTFOLIO_NOT_INITIALIZED"
  | "INSTRUMENT_NOT_FOUND"
  | "NO_MARKET_DATA"
  | "NO_MARKET_SESSION"
  | "INVALID_DATE_RANGE"
  | "INVALID_QUERY"
  | "COVERAGE_INSUFFICIENT"
  | "UNSUPPORTED_PRICE_BASIS"
  | "INVALID_PROVIDER_DATA"
  | "PROVIDER_UNAVAILABLE"
  | "RATE_LIMITED"
  | "CORRUPT_LEDGER"
  | "BUY_NOT_FOUND"
  | "INVALID_VOID_TARGET"
  | "BUY_ALREADY_VOIDED"
  | "SCENARIO_ARCHIVED";

export class DomainError extends Error {
  constructor(
    readonly code: DomainErrorCode,
    message: string,
  ) {
    super(`${code}: ${message}`);
    this.name = "DomainError";
  }
}
